import crypto from 'node:crypto';
const API_BASE='https://api.meinbuero.de/openapi',SUPABASE_URL_FALLBACK='https://dbaiwcqoigqgknmtctwl.supabase.co',SUPABASE_PROJECT_HOST='dbaiwcqoigqgknmtctwl.supabase.co';
function cleanUrl(v,f=''){const r=String(v||f||'').trim().replace(/\s+/g,'');if(!r)return'';let u=/^https?:\/\//i.test(r)?r:`https://${r.replace(/^\/+/, '')}`;u=u.replace(/\/$/,'');try{const p=new URL(u);return p.hostname===SUPABASE_PROJECT_HOST?`${p.protocol}//${p.hostname}`:SUPABASE_URL_FALLBACK}catch{return SUPABASE_URL_FALLBACK}}
function b64(v){const n=String(v||'').replace(/-/g,'+').replace(/_/g,'/');return Buffer.from(n+'='.repeat((4-n.length%4)%4),'base64')}
async function verify(req){const su=cleanUrl(process.env.SUPABASE_URL,SUPABASE_URL_FALLBACK),a=String(req.headers.authorization||'');if(!a.startsWith('Bearer '))throw Error('UNAUTHORIZED');const t=a.slice(7).trim(),p=t.split('.');if(p.length!==3)throw Error('UNAUTHORIZED');let h,d;try{h=JSON.parse(b64(p[0]).toString());d=JSON.parse(b64(p[1]).toString())}catch{throw Error('UNAUTHORIZED')}if(!d?.sub||!d?.exp||d.exp*1000<=Date.now()||(typeof d.iss==='string'&&!d.iss.startsWith(`${su}/auth/v1`)))throw Error('UNAUTHORIZED');const jr=await fetch(`${su}/auth/v1/.well-known/jwks.json`,{cache:'no-store'}),j=await jr.json().catch(()=>({})),k=Array.isArray(j?.keys)?j.keys.find(x=>!h.kid||x.kid===h.kid):null;if(!jr.ok||!k)throw Error('UNAUTHORIZED');try{const key=crypto.createPublicKey({key:k,format:'jwk'}),data=Buffer.from(`${p[0]}.${p[1]}`),sig=b64(p[2]);let ok=false;if(h.alg==='RS256')ok=crypto.verify('RSA-SHA256',data,key,sig);else if(h.alg==='ES256')ok=crypto.verify('sha256',data,{key,dsaEncoding:'ieee-p1363'},sig);if(!ok)throw Error()}catch{throw Error('UNAUTHORIZED')}return d.sub}
function detail(data){const m=data?.meta||{},out=[];for(const [group,val] of Object.entries(m)){for(const x of(Array.isArray(val)?val:[val])){if(x?.missingProperty)out.push(`${group}: missing ${x.missingProperty}`);if(x?.code)out.push(`${group}: ${x.code}`)}}return out.join(' | ')}
async function token(i){const k=String(process.env.WISO_API_KEY||'').trim(),s=String(process.env.WISO_API_SECRET||'').trim();if(!k||!s)throw Error('WISO_NOT_CONFIGURED');if(!i)throw Error('OWNERSHIP_ID_MISSING');const r=await fetch(`${API_BASE}/auth/token`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${k}:${s}`).toString('base64')}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({ownershipId:String(i).trim()})}),raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok){const e=Error(detail(d)||d?.message||`WISO Anmeldung fehlgeschlagen (${r.status}).`);e.status=r.status;e.data=d;throw e}const t=d?.Token||d?.token||d?.accessToken||d?.access_token;if(!t)throw Error('WISO hat kein Zugriffstoken geliefert.');return t}
async function wf(path,t,opt={}){const r=await fetch(`${API_BASE}${path}`,{...opt,headers:{Authorization:`Bearer ${t}`,Accept:'application/json',...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}}),raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{d={raw}}if(!r.ok){const e=Error(detail(d)||d?.message||d?.detail||`WISO API Fehler (${r.status}).`);e.status=r.status;e.data=d;console.error('WISO_API_VALIDATION',JSON.stringify({path,status:r.status,detail:detail(d),body:d}));throw e}return d}
function city(v=''){const x=String(v).trim(),m=x.match(/^(\d{5})\s+(.+)$/);return m?{zipCode:m[1],city:m[2]}:{zipCode:'',city:x}}
function cp(c={}){const p=city(c.city);return{email:c.email||undefined,phone:c.phone||undefined,customerDefaultAddress:{billingAddress:{kind:'company',companyName:c.name||'',firstName:c.contact_person||'',lastName:'',street:c.street||'',zipCode:p.zipCode,city:p.city,countryIso:'DE'}}}}
function id(o){return o?.id||o?.data?.id||o?.customerId||o?.orderId||o?.invoiceId||o?.data?.customerId||o?.data?.orderId||o?.data?.invoiceId||null}
function positions(doc={},metaType='position'){const a=Array.isArray(doc?.payload?.positions)?doc.payload.positions:Array.isArray(doc.positions)?doc.positions:[];return a.filter(p=>String(p?.desc||p?.description||'').trim()||Number(p?.price||0)!==0).map((p,i)=>{const title=String(p?.desc||p?.description||`Position ${i+1}`).trim(),amount=Number(p?.qty??p?.quantity??1)||1,priceNet=Number(p?.price??p?.unitPrice??0)||0,vatPercent=Number(p?.vatRate??19),priceGross=Math.round((priceNet*(1+vatPercent/100)+Number.EPSILON)*100)/100;return{amount,discountPercent:0,vatPercent,title,description:title,priceNet,priceGross,showDescription:true,unit:'Stück',metaData:{type:metaType}}})}
async function customer(t,c={}){if(!c?.name)throw Error('Kundenname fehlt.');if(c.wisoId)return c.wisoId;if(c.email){try{const f=await wf(`/customer?offset=0&limit=20&search=${encodeURIComponent(c.email)}`,t),l=f?.data||f?.items||f?.customers||f?.rows||[],h=Array.isArray(l)?l.find(x=>String(x?.email||'').toLowerCase()===String(c.email).toLowerCase()):null,hit=id(h);if(hit)return hit}catch{}}const made=await wf('/customer/',t,{method:'POST',body:JSON.stringify(cp(c))}),cid=id(made);if(!cid)throw Error('WISO hat nach dem Anlegen des Kunden keine Kunden-ID geliefert.');return cid}
async function order(t,cid,doc={}){const base={customerId:cid,subject:String(doc?.payload?.subject||doc?.title||doc?.document_number||'HandwerkPilot Rechnung').trim(),orderDate:String(doc?.payload?.date||'').trim()||new Date().toISOString().slice(0,10),note:String(doc?.payload?.note||'').trim()||undefined};const types=['position','POSITION','manual','MANUAL','custom','CUSTOM','service','SERVICE','text','TEXT'];let last;for(const metaType of types){const ps=positions(doc,metaType);if(!ps.length)throw Error('Die Rechnung enthält keine Positionen.');const payload={...base,positions:ps};try{const result=await wf('/order/',t,{method:'POST',body:JSON.stringify(payload)});console.log('WISO_ORDER_META_TYPE_OK',metaType);return result}catch(e){last=e;console.error('WISO_ORDER_META_TYPE_TRY',JSON.stringify({metaType,error:e?.data||e?.message}));const invalid=String(e?.message||'').includes('positionMeta.type')&&String(e?.message||'').includes('INVALID');if(!invalid){console.error('WISO_ORDER_PAYLOAD',JSON.stringify({payload,error:e?.data||e?.message}));throw e}}}throw last||Error('WISO Positionsart konnte nicht bestimmt werden.')}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Nur POST erlaubt.'});try{await verify(req);const b=req.body||{},a=String(b.action||'').trim(),t=await token(String(b.ownershipId||'').trim());if(a==='status')return res.status(200).json({connected:true,account:await wf('/setting/account',t)});if(a==='createCustomer')return res.status(200).json({ok:true,customerId:await customer(t,b.customer||{})});if(a==='syncInvoice'){if(b?.document?.document_type&&b.document.document_type!=='rechnung')return res.status(400).json({error:'Nur Rechnungen können an WISO übertragen werden.'});const cid=await customer(t,b.customer||{}),o=await order(t,cid,b.document||{}),oid=id(o);if(!oid)throw Error('WISO hat keine Auftrags-ID zurückgegeben.');const inv=await wf(`/order/${encodeURIComponent(oid)}/invoice`,t,{method:'POST'});return res.status(200).json({ok:true,customerId:cid,orderId:oid,invoiceId:id(inv),order:o,invoice:inv})}return res.status(400).json({error:'Unbekannte WISO-Aktion.'})}catch(e){const m=String(e?.message||e);if(m==='UNAUTHORIZED')return res.status(401).json({error:'Bitte erneut bei HandwerkPilot anmelden.'});if(m==='WISO_NOT_CONFIGURED')return res.status(503).json({error:'WISO_API_KEY und WISO_API_SECRET fehlen noch in Vercel.'});if(m==='OWNERSHIP_ID_MISSING')return res.status(400).json({error:'Bitte zuerst die WISO Ownership-ID eintragen.'});console.error('HandwerkPilot WISO Error:',e);return res.status(502).json({error:m||'WISO-Verbindung fehlgeschlagen.',details:e?.data||undefined})}}
